name: ContinuousIntegrationPipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1.11
      with:
        cmake-version: '3.5.x'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libboost-program-options-dev
        sudo apt-get install -y libyaml-cpp-dev
        sudo apt-get install -y libdart-all-dev
        sudo apt-get install -y libidn11
        
    - name: Clone and Build OMPL
      run: |
        git clone https://github.com/aorthey/ompl.git ompl-custom
        cd ompl-custom
        git checkout FibrationTrees
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/ompl-custom
        make -j$(nproc)
        sudo make install
        
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ..
    - name: Build
      run: |
        cd build
        make -j$(nproc)
        
    - name: Run Tests
      run: |
        cd build
        ctest --output-on-failure

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: build/Testing/Temporary/LastTest.log
