name: ContinuousIntegrationPipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update -y -qq &&
        sudo apt-get install -y -qq \
        cmake \
        libboost-filesystem-dev \
        libboost-program-options-dev \
        libboost-serialization-dev \
        libboost-system-dev \
        libboost-test-dev \
        libeigen3-dev \
        libflann-dev \
        libode-dev \
        libtriangle-dev \
        libyaml-cpp-dev \
        libdart-all-dev \
        libdart-gui-osg-dev \
        libdart-utils-dev \
        libdart-utils-urdf-dev \
        libdart-collision-bullet-dev \
        libdart-external-ikfast-dev \
        libdart-external-imgui-dev \
        libdart-external-lodepng-dev \
        libgtest-dev \
        python3-numpy
        wget http://mirrors.kernel.org/ubuntu/pool/main/libi/libidn/libidn11_1.33-2.2ubuntu2_amd64.deb
        sudo apt install ./libidn11_1.33-2.2ubuntu2_amd64.deb
        
    - name: Clone and Build OMPL
      run: |
        git clone https://github.com/aorthey/ompl.git ompl-custom
        cd ompl-custom
        git checkout FibrationTrees
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/ompl-custom
        make -j$(nproc) && make test && sudo make install

    - name: Run Ompl Unit Tests
      run: |
        cd ompl-custom/build
        ctest --output-on-failure
        
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake ..

    - name: Unit Tests
      run: |
        cd build
        ctest --output-on-failure -L unit

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ${{github.workspace}}/Testing/Temporary/LastUnitTests.log
